import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,onSnapshot,getDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);let data=[],unsubscribe=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const validMap=raw=>{try{if(!raw)return '';const u=new URL(raw);return u.protocol==='https:'?u.href:''}catch{return ''}};
$('login').onclick=async()=>{$('loginMsg').textContent='';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch{$('loginMsg').textContent='Sign-in failed. Check your admin ID and password.'}};$('signOut').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(unsubscribe){unsubscribe();unsubscribe=null}$('loginBox').classList.toggle('hidden',!!u);$('adminContent').classList.add('hidden');$('signOut').classList.toggle('hidden',!u);$('accessDenied').classList.add('hidden');if(!u)return;try{const s=await getDoc(doc(db,'staff',u.uid));if(!s.exists()||s.data().role!=='admin'){ $('accessDenied').classList.remove('hidden');await signOut(auth);return;}$('adminContent').classList.remove('hidden');listen()}catch{$('loginBox').classList.add('hidden');$('accessDenied').classList.remove('hidden');await signOut(auth)}});
function listen(){unsubscribe=onSnapshot(collection(db,'customers'),s=>{data=s.docs.map(d=>({id:d.id,...d.data()}));render()},()=>{$('msg').textContent='Unable to load customers. Check Firestore rules.'})}function render(){data.sort((a,b)=>String(a.location).localeCompare(String(b.location))||String(a.name).localeCompare(String(b.name)));$('total').textContent=data.length;$('list').innerHTML=data.length?data.map(c=>`<div class="item"><div><b>${esc(c.name)}</b><small>${esc(c.location)} · ${esc(c.phone)}${c.delivered?' · Delivered':''}</small></div><div><button class="edit" data-id="${c.id}">Edit</button><button class="delete" data-id="${c.id}">Delete</button></div></div>`).join(''):'<div class="empty">No customers yet.</div>';document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>edit(data.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{const c=data.find(x=>x.id===b.dataset.id);if(c&&confirm(`Delete ${c.name}?`))await deleteDoc(doc(db,'customers',c.id))})}
$('form').onsubmit=async e=>{e.preventDefault();$('msg').textContent='';const mapLink=validMap($('map').value.trim());if($('map').value.trim()&&!mapLink){$('msg').textContent='Map link must be a valid HTTPS URL.';return}const d={name:$('name').value.trim(),phone:$('phone').value.trim(),location:$('location').value.trim(),mapLink,address:$('address').value.trim()},id=$('id').value;if(!d.name||!d.phone||!d.location){$('msg').textContent='Name, phone and location are required.';return}try{if(id){const existing=data.find(x=>x.id===id);await updateDoc(doc(db,'customers',id),{...d,delivered:existing?.delivered===true})}else await addDoc(collection(db,'customers'),{...d,delivered:false});reset();$('msg').textContent='Saved successfully.'}catch{$('msg').textContent='Save failed. Check Firestore rules.'}};function edit(c){$('id').value=c.id;$('name').value=c.name||'';$('phone').value=c.phone||'';$('location').value=c.location||'';$('map').value=c.mapLink||'';$('address').value=c.address||'';$('title').textContent='Edit customer';scrollTo({top:0,behavior:'smooth'})}function reset(){$('form').reset();$('id').value='';$('title').textContent='Add customer'}$('cancel').onclick=reset;
